### ISSUE TITLE
DHCP configuration invalid

### ISSUE THREAD

**Issue by disconn3ct** [k8s-at-home/pod-gateway#31]
# Details

**What steps did you take and what happened:**
Following https://docs.k8s-at-home.com/guides/pod-gateway/ results in the terminal's init pod throwing errors:
```
Internet Systems Consortium DHCP Client 4.4.2
Copyright 2004-2020 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

/etc/dhclient.conf line 3: semicolon expected.
link-timeout 10;
              ^
/etc/dhclient.conf line 4: semicolon expected.
reboot 
 ^
/etc/dhclient.conf line 15: no option named require in space dhcp
  require routers,
   ^
/etc/dhclient.conf line 18:  : expected option name.
 }
  ^
/etc/dhclient.conf line 18: unterminated interface declaration.

^
Listening on LPF/vxlan0/b6:e1:31:a1:41:9c
```

**What did you expect to happen:**
Valid configs

**Anything else you would like to add:**
Looks like https://github.com/k8s-at-home/pod-gateway/commit/cd7c089e6e543a75fa613e15db09bceb4f32f487#diff-d54596a8123109273f35d08877bd864894464deefc06410563ac9ff0f314432eR49-R52 didn't close out the lists

**Additional Information:**

**Comment by angelnu** [comment]
This Bug remained long hidden.  Thanks for reporting.I am away from my cluster to check but the bug should affect everyone.  Does it prevent the pod to work?On 31 May 2022 21:04, Dis ***@***.***> wrote:
Details
What steps did you take and what happened:
Following https://docs.k8s-at-home.com/guides/pod-gateway/ results in the terminal's init pod throwing errors:
Internet Systems Consortium DHCP Client 4.4.2
Copyright 2004-2020 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

/etc/dhclient.conf line 3: semicolon expected.
link-timeout 10;
              ^
/etc/dhclient.conf line 4: semicolon expected.
reboot 
 ^
/etc/dhclient.conf line 15: no option named require in space dhcp
  require routers,
   ^
/etc/dhclient.conf line 18:  : expected option name.
 }
  ^
/etc/dhclient.conf line 18: unterminated interface declaration.

^
Listening on LPF/vxlan0/b6:e1:31:a1:41:9c


What did you expect to happen:
Valid configs

Anything else you would like to add:
Looks like cd7c089 didn't close out the lists

Additional Information:

**Comment by disconn3ct** [comment]
My install is broken, but I don't think this config is the root cause. (I'm fighting on Calico difficulty.) The client does look like it is requesting DHCP, but just timing out. I suspect something in the vxlan bringup is wrong. (It looks right.. it pings the gateway, does the magic, then .. nada. DHCPDISCOVER into the void.)

**Comment by angelnu** [comment]
@disconn3ct - I had missed the fix level in the tag - I rebuilt the release with the right tag.
