### ISSUE TITLE
dnsmasq crash/exit does not crash container

### ISSUE THREAD

**Issue by disconn3ct** [k8s-at-home/pod-gateway#33]
# Details

**What steps did you take and what happened:**

When dnsmasq is given a bad configuration and aborts, the container continues. Only killing `inotifyd` causes it to exit.

This also shows in a slow shutdown time, as inotifyd does not exit quickly.

**What did you expect to happen:**

dnsmasq failing should cause the container to exit.

**Anything else you would like to add:**

I'm still trying to reproduce the bad configuration separately to go in a different bug. In the DNS settings it built `/local/1.1.1.1 \n2.2.2.2`, which cause dnsmasq to complain and exit.

**Additional Information:**

It is easy to reproduce; exec a shell in the container and kill various things. Only inotifyd will cause a restart.

**Comment by angelnu** [comment]
@disconn3ct - I fixed this with https://github.com/k8s-at-home/pod-gateway/commit/2870a9d6c5317a0114426a02219311912a85dac2

For testing please use the `latest` container tag - I would build an official release afterwards.

**Comment by disconn3ct** [comment]
This seems to still be an issue in v1.7.0 

Quick test:
```
$ k exec -ti deploy/gateway-pod-gateway -- bash
bash-5.1# ps axw                                                                                                              
PID   USER     TIME  COMMAND                                                                                                  
    1 root      0:00 {gateway_sidecar} /bin/bash /bin/gateway_sidecar.sh                                                      
   16 dnsmasq   0:00 dnsmasq -k                                                                                               
   17 root      0:00 inotifyd /bin/copy_resolv.sh /etc/resolv.conf ce                                                         
   22 root      0:00 bash                                                                                                     
   36 root      0:00 ps axw                                                                                                   
bash-5.1# kill 16                                                                                                             
bash-5.1# ps axw                                                                                                              
PID   USER     TIME  COMMAND
    1 root      0:00 {gateway_sidecar} /bin/bash /bin/gateway_sidecar.sh
   17 root      0:00 inotifyd /bin/copy_resolv.sh /etc/resolv.conf ce
   22 root      0:00 bash
   53 root      0:00 ps axw
``` and it is still healthy about 5 minutes later.

**Comment by angelnu** [comment]
Please check https://github.com/angelnu/pod-gateway/commit/e77c19f7ecb8ac27ef65373402b290e7ec631efe

You might use the dev container:
 ```
 # See https://github.com/k8s-at-home/charts/blob/master/charts/stable/pod-gateway/values.yaml
  values:

    image:
      repository: ghcr.io/angelnu/pod-gateway
      # Use dev version
      pullPolicy: Allways
      tag: dev
```
I will do an official release next.
