### ISSUE TITLE
Allow Ping-count configuration in the Client-Sidecar 

### ISSUE THREAD

**Issue by MichaelWasher** [k8s-at-home/pod-gateway#36]
# Details
When deploying the Pod-gateway, I am using this to ensure all traffic is forwarded externally using a given egress IP and egress machine. Sometimes these 'exit-nodes' may be separated over the internet (i.e. tunnelling traffic to different geography before being sent out to their destination)

As ICMP+VXLAN doesn't provide a reliable connection standard, intermittently I'm seeing small amounts of packet loss resulting in the failures of the client side-cars.

In the links below, the ping count is set to 1. I think this should be configurable with an environment variable and default to 1.
https://github.com/k8s-at-home/pod-gateway/blob/main/bin/client_sidecar.sh#L19
https://github.com/k8s-at-home/pod-gateway/blob/main/bin/client_init.sh#L48
https://github.com/k8s-at-home/pod-gateway/blob/main/bin/client_init.sh#L93

This will allow the ability to set an arbitrary standard of reliability before restarting.

---- Additional:
As an additional bonus, it'll be really easy to configure with the Pod-Gateway HelmChart by just adding an additional env var to the `settings` object.

**Comment by MichaelWasher** [comment]
https://github.com/k8s-at-home/pod-gateway/pull/37

**Comment by angelnu** [comment]
Related v1.7.0 with your pr. Thanks
