### ISSUE TITLE
gateway misdetects 'local' dns if the container crashes

### ISSUE THREAD

**Issue by disconn3ct** [k8s-at-home/pod-gateway#41]
https://github.com/k8s-at-home/pod-gateway/blob/a9ba9079c3504ff3efde12a39ab4575896c9a961/bin/gateway_sidecar.sh#L12 it accepts multiple entries, and assumes they are internal DNS. On a normal start, this appears to be a safe assumption, but if the container (not pod) is restarted it will see the post-VPN dns and apply multiple public dns servers as a multi-line string.

This is .. not ideal.

This results in `dnsmasq: bad option at line 31 of /etc/dnsmasq.d//pod-gateway.conf`:
Script output:
```
+ K8S_DNS='103.86.96.100
103.86.99.100'
```
and the config gets
```
  # Send local DNS queries to the K8S DNS server
  server=/local/103.86.96.100
103.86.99.100
```

**Comment by angelnu** [comment]
it should be fixed in https://github.com/angelnu/pod-gateway/releases/tag/v1.8.0
