### ISSUE TITLE
gateway_init.sh exiting early causing pod init failure

### ISSUE THREAD

**Issue by cbc02009** [k8s-at-home/pod-gateway#42]
# Details

**What steps did you take and what happened:**
I am trying to enable a vpn gateway using the Helm release. Config files available [here](https://github.com/cbc02009/k8s-home-ops/blob/07f09d4807eaa931b71c13cb775aa47a51d374e9/cluster/manifests/vpn/downloads-gateway/values.yaml) in my flux repo.

The pod init container routes exits early while running the gateway_init.sh script, so pod creation fails. I'm thinking it fails on either [this line](https://github.com/k8s-at-home/pod-gateway/blob/a9ba9079c3504ff3efde12a39ab4575896c9a961/bin/gateway_init.sh#L24) or the next one.

**What did you expect to happen:**
The pod to finish creation successfully.

**Anything else you would like to add:**
the last couple lines of the log from the init container are 
```
++ VXLAN_ID=43
++ VXLAN_IP_NETWORK=172.16.1
++ cat /proc/sys/net/ipv4/ip_forward
+ [[ 1 -ne 1 ]]
+ VXLAN_GATEWAY_IP=172.16.1.1
+ ip link add vxlan0 type vxlan id 43 dev eth0 dstport 0
RTNETLINK answers: File exists
+ true
+ ip addr add 172.16.1.1/24 dev vxlan0
RTNETLINK answers: File exists
+ true
+ ip link set up dev vxlan0
+ ip rule add from all lookup main suppress_prefixlength 0 preference 50
RTNETLINK answers: File exists
```

**Additional Information:**
I'm running Kubernetes v1.24.4 on an Arch host with kernel 5.19.4-arch1-1 

Please let me know if there's any more information I can provide.

**Comment by cbc02009** [comment]
@angelnu Thank you!!

**Comment by angelnu** [comment]
Correct - with the request to deprecate k8s-at-home repo I will move my components to my user id and maintain there. For the time being please change the image manually in the helm chart until I move that as well.
